### ISSUE TITLE
Topics and replies held in pending with no notification to approve the posts

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/boss-child#113]
This has become a widespread issue on not just HC but also SAH. 

https://hcommons.org/wp/wp-admin/edit.php?post_type=reply

https://hcommons.org/wp/wp-admin/edit.php?post_type=topic

Even users who have posted successfully in that group are getting caught in the pending queue.

**Comment by mikethicke** [comment]
Bypassing bbpress comment moderation. If discussion spam becomes a problem we might need to revisit this, but would also need a better interface for moderating topics and replies.

- [boss-child-113-bypass-bbpress-comment-moderation](https://github.com/MESH-Research/hc-custom/commit/e0a16a4c7a4e3e00e27339798c7913e224b0d061)
