### ISSUE TITLE
MODS Modifications for FAST subjects

### ISSUE THREAD

**Issue by ericknappe** [MESH-Research/boss-child#122]

**Comment by ericknappe** [comment]
Currently we write subjects to Fedora MODS object containing just the term name, we do not currently use a known authority for the values

<subjects>
  <subject>Toads</subject>
</subjects>

With the current software, FAST Subjects will be written like this

<subjects>
  <subject>1151755:Toads:Topic</subject>
</subjects>

For interoperability, subjects using a known authority should be identified as such.

Example Format (taken from MODS 3.5, we are currently writing MODS 3.4)
        
<subject authority="lcsh" authorityURI="http://id.loc.gov/authorities/subjects">
  <topic valueURI="http://id.loc.gov/authorities/subjects/sh85070736">Journalism</topic>
  <topic valueURI="http://id.loc.gov/authorities/subjects/sh00005651">Political aspects</topic>
  <geographic valueURI="http://id.loc.gov/authorities/names/n78095330">United States</geographic>
</subject>

The task here is to identify the proper values for authority, authorityURI, valueURI and facet to modify the data added to the MODS record. 

NOTE: The example above shows a compound subject which is a scope that may be beyond our current plans. We are breaking compound subjects into discrete subjects and would store and show the example above as 3 separate subjects

<subject authority="lcsh" authorityURI="http://id.loc.gov/authorities/subjects">
  <topic valueURI="http://id.loc.gov/authorities/subjects/sh85070736">Journalism</topic>
</subject>
<subject authority="lcsh" authorityURI="http://id.loc.gov/authorities/subjects">
  <topic valueURI="http://id.loc.gov/authorities/subjects/sh00005651">Political aspects</topic>
</subject>
<subject authority="lcsh" authorityURI="http://id.loc.gov/authorities/subjects">
  <geographic valueURI="http://id.loc.gov/authorities/names/n78095330">United States</geographic>
</subject>

Getting back to our simple toad example, we need to create the a subject using the following format and replacing XXXX with the appropriate values.

<subjects>
  <subject authority="XXXX" authorityURI="XXXX">
    <topic valueURI="XXXX>Toads</topic>
  </subject>
</subjects>

MODS "Lite" subject documentation:
https://www.loc.gov/standards/mods/v3/mods-userguide-elements.html#subject

**Comment by amareshjoshi** [comment]
there's no `<subjects>` level tags. it's just <subject>
```
<subject>Lizards</subject>
<subject>Toadss</subject>
<!-- etc -->
```

**Comment by amareshjoshi** [comment]
Completed.
