### ISSUE TITLE
Society (MLA) enrollment fails due to exception thrown by the Novi API in sue for ARLIS

### ISSUE THREAD

**Issue by ericknappe** [MESH-Research/boss-child#135]

**Comment by ericknappe** [comment]
The HCConfirmer plugin loops through all org identity sources cecking for active membership. A new source, the NOVI API, is throwing an exception rather than just returning an inactive status.
1. Catch and handle this exception.
2. Request SCG rethink throwing an exception in this case if possible.

**Comment by ericknappe** [comment]
MLA Commons enrollment failed, but Humanities Commons enrollment succeeded. I'll like at the differences between enrollment flows.

**Comment by ericknappe** [comment]
Interim fix (trapping the exception) is in place. MLA enrollment of hctester40 now completes in dev.

1. Novi plugin should probably not throw an exception here. I'll open a ticket with SCG.
2. The MLA conditional code was intended to check MLA expiration date and is checking all APIs. I'll change this to process only the MLA Org id.

**Comment by mikethicke** [comment]
@bjr70 Do you want to give this a try?

**Comment by bjr70** [comment]
Yup, I'll do that after lunch.

**Comment by bjr70** [comment]
This is fixed.
