### ISSUE TITLE
HASTAC enrollment needs to be treated like an HC enrollment by the HCConfirmer plugin

### ISSUE THREAD

**Issue by ericknappe** [MESH-Research/boss-child#136]

**Comment by ericknappe** [comment]
HC membership is automatic. Up until now all other memberships have had to have active membership in a partner society DB. HASTAC needs to be handled the same way has HC and this requires a few changes the the HCConfirmer plugin.

**Comment by bjr70** [comment]
@ericknappe @mikethicke has this been completed?
