### ISSUE TITLE
Initial Testing of Refreshed Theme

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/boss-child#144]
Initial testing of the refreshed theme should take place on https://hcommons-2.dev/ . This testing can take place while theme development is in progress. The aim of this testing is to identify work that needs to be done on the refreshed version of the theme to make it production-ready. 

Issues that are blocking issues---issues that *must* be resolved before the theme can be pushed to production---should be added to the "Develop no-sidebar carousel theme refresh" epic (https://github.com/MESH-Research/boss-child/issues/138).

If applicable, add notes to existing issues. Eg. for the menu bar: https://github.com/MESH-Research/boss-child/issues/141 .

Issues should be created in the boss-child repository.

Non-critical issues can be created in the boss-child repository but shouldn't be added to the epic.

**Comment by mikethicke** [comment]
Thanks @kfitz!

I'd like others' opinions on whether autoscroll should be on for the modal. My concern is that if autoscroll is off, the vast majority of users will never see anything beyond the first slide.

**Comment by babaklar** [comment]
I'm thinking we should have autoscroll for that reason; if it doesn't automatically scroll, users won't realize there are other slides. At same time, I'm thinking we don't want it to scroll too quickly because it can be distracting, so maybe about 5-8 seconds per slide?

**Comment by kfitz** [comment]
I can probably live with a slow scroll :)

**Comment by mikethicke** [comment]
The web-accessibility page says that you shouldn't have autoscroll, but the w3 page doesn't say that and their working example does autoscroll.

The current plugin we can slow down. It also has keyboard control and pauses on hover. The main accessibility feature it is missing is a play / pause button. I spent some time looking at alternative plugins and couldn't find an acceptable free alternative that does have a play/pause button. I did find a freemium plugin that is slightly more attractive and configurable than the current one.

If a play / pause button is a must-have if we're doing a carousel, we might re-consider the carousel option? The pages Larissa referenced are at least ambivalent about the desirability of carousels from an accessibility standpoint.

**Comment by kfitz** [comment]
What if we were to do something crazy clean like this? https://buffer.com

It eliminates the ability to highlight content on the front page, but makes super clear what we are and how to get started. (And then maybe we can start working on a different logged-in front page that does highlight content?)

**Comment by mikethicke** [comment]
Do you mean just a static image where the carousel is currently?

**Comment by kfitz** [comment]
I like that idea. (I'm poking around to find other carousel-free homepage examples that might be instructive.)

**Comment by bjr70** [comment]
I like that a lot. I also like the "building blocks of the commons" section.

**Comment by mikethicke** [comment]
Yep--we could do a 3-column thing like CUNY pretty easily.
