### ISSUE TITLE
Design content area for HC refresh

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/boss-child#147]
Redesign the content area of the refreshed homepage. This is done in the WordPress block editor. 

Current redesign:

<img width="1131" alt="Screen Shot 2022-07-05 at 3 39 16 PM" src="https://user-images.githubusercontent.com/26980498/177403008-1ceb924a-7a7d-4a44-9c9e-65c1fd15ceee.png">

- Humanites Commons logo?
- Buttons
- Color scheme
- Welcome blurb
- Carousel behavior (scroll speed, auto scroll, etc.)

This isn't directly part of the theme refresh, but is required by it. Since this is done in the block editor, Mike doesn't necessarily have to be the one that implements it.

(We could also consider redesigning interior site pages in the block editor, which would be separate issues.)

Larissa is working on planning carousel content as part of a separate issue: https://github.com/mesh-research/commons/issues/383

**Comment by bjr70** [comment]
I've taken a stab at the home page. I've re-used the slider on the homepage to feature the CORE collections, but we could do something else there. The collections link to prod, not hcdev-2. Doesn't look like CORE is working on this box. https://hcommons-2.dev/

**Comment by kfitz** [comment]
I'm wondering if we might do something like:

- Top section, two column: Welcome + text + getting started // graphic of some kind
- Second section, three column (each icon + text): Members // Groups // CORE (see front page of [CUNY AC](https://commons.gc.cuny.edu)
- Third section, one column: About or Help or Recent activity

All this with a bit more white space so it feels a bit less busy. I'd be happy to work on a version of this if you like.

**Comment by bjr70** [comment]
So I tried to incorporate some of your suggestions with a few ideas that Mike had earlier. I got booted out and can't log back in so it's not quite what I intended, but might be closer? https://hcommons-2.dev/

**Comment by kfitz** [comment]
It's definitely closer. Do you mind if I pop in and do some tinkering?

**Comment by bjr70** [comment]
Not at all! It’s not perfect and could use another eye.

**Comment by bjr70** [comment]
This is on https://hcommons-2.dev for review

**Comment by bjr70** [comment]
Closing.
