### ISSUE TITLE
Design content for CORE landing page

### ISSUE THREAD

**Issue by kfitz** [MESH-Research/boss-child#148]
This page needs a total overhaul! Right now it contains:

- Right sidebar: About CORE / Why CORE?
- Top center: Welcome to CORE / Buttons for upload and find content
- Center left: Collections
- Center right: Recent deposits / Recommended for you (logged out/in)

We should consider what really needs to be conveyed to users on first arriving at the repo. Perhaps we get rid of the right sidebar and use the main content area for:

- Top left: Welcome to CORE!
- Just below: About
- Just below that: Buttons for upload / find content
- Top right: Why CORE?

**Comment by bjr70** [comment]
Proposed new design here: https://hcommons-2.dev/core/

**Comment by bjr70** [comment]
I see now that it's the HUMCore template. We could get rid of that sidebar, but I think it might work in this case.

**Comment by kfitz** [comment]
I think it looks great. Might be able to close this issue.

**Comment by bjr70** [comment]
Fantastic! I'm going to go ahead and close this. We can always reopen it if we want to make changes.
