### ISSUE TITLE
Upgrade php to 7.4 on comamage stack

### ISSUE THREAD

**Issue by ericknappe** [MESH-Research/boss-child#151]

**Comment by ericknappe** [comment]
Comanage has very specific php requirements. See  https://spaces.at.internet2.edu/display/COmanage/COmanage+Installation+-+PHP#COmanageInstallationPHP-PHPBuildOptions

Upgrade develop first to allow testing of the next comanage verison.

**Comment by mikethicke** [comment]
PHP is updated to 7.4 on dev.
